language: perl
cache:
    - apt
    - ccache
notifications:
  irc: "chat.freenode.net#lua-resty-waf"
  webhooks: https://www.cryptobells.com/endpoint
env:
    - V_OPENRESTY=1.9.15.1 DATE=20160714 TEST=unit
    - V_OPENRESTY=1.9.15.1 DATE=20160714 TEST=acceptance
    - V_OPENRESTY=1.9.15.1 DATE=20160714 TEST=regression
services:
    - memcached
    - redis
install:
    - cpanm -v --notest Test::Nginx
before_script:
    - sudo apt-get update -q
    - sudo apt-get install libssl-dev lua5.1 -y
    - wget http://cdn.cryptobells.com/openresty-$V_OPENRESTY-$DATE.tar.bz2
    - sudo tar -jxvf openresty-$V_OPENRESTY-$DATE.tar.bz2 -C /usr/local/
    - sudo ln -fs $(pwd)/lib/resty/* /usr/local/openresty/lualib/resty/
    - sudo ln -fs $(pwd)/lib/*.so /usr/local/openresty/lualib/
    - sudo ln -fs $(pwd)/rules /usr/local/openresty/lualib/
script:
  - PATH=/usr/local/openresty/nginx/sbin:$PATH prove -r t/$TEST
  - ./tools/lua-releng -L
